import { Bell, Check, CheckCheck } from "lucide-react";

import { PageHeader } from "@/components/layout/page-header";

import { Badge } from "@/components/ui/badge";

import { Button } from "@/components/ui/button";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  markAllNotificationsReadAction,
  markNotificationReadAction,
} from "@/features/notifications/actions";

import { getNotifications } from "@/features/notifications/api/get-notifications";

type Props = {
  params: Promise<{
    organizationId: string;
  }>;
};

function getKindLabel(kind: "INFO" | "SUCCESS" | "WARNING") {
  switch (kind) {
    case "SUCCESS":
      return "Success";

    case "WARNING":
      return "Warning";

    default:
      return "Info";
  }
}

export default async function NotificationsPage({ params }: Props) {
  const { organizationId } = await params;

  const notifications = await getNotifications(organizationId, 100);

  const markAllAction = markAllNotificationsReadAction.bind(
    null,
    organizationId,
  );

  return (
    <>
      <PageHeader
        title="Notifications"
        description="Operational updates produced asynchronously from warehouse events."
      />

      <div className="flex items-center justify-between gap-4 rounded-lg border bg-card px-4 py-3">
        <div>
          <p className="text-sm font-medium">
            {notifications.unreadCount} unread
          </p>

          <p className="text-xs text-muted-foreground">
            Notifications are generated by the background outbox worker.
          </p>
        </div>

        {notifications.unreadCount > 0 ? (
          <form action={markAllAction}>
            <Button type="submit" variant="outline" size="sm">
              <CheckCheck className="size-4" />
              Mark all read
            </Button>
          </form>
        ) : null}
      </div>

      {notifications.items.length === 0 ? (
        <div className="flex min-h-64 items-center justify-center rounded-lg border border-dashed bg-muted/20">
          <div className="max-w-sm text-center">
            <Bell className="mx-auto size-8 text-muted-foreground" />

            <p className="mt-3 text-sm font-medium">No notifications yet</p>

            <p className="mt-1 text-sm text-muted-foreground">
              Submit or receive purchase orders, or process sales orders, to
              create asynchronous notifications.
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-3">
          {notifications.items.map((notification) => {
            const markReadAction = markNotificationReadAction.bind(
              null,
              organizationId,
              notification.id,
            );

            return (
              <Card
                key={notification.id}
                className={notification.readAt ? "opacity-70" : undefined}
              >
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between gap-4">
                    <div className="min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <CardTitle className="text-base">
                          {notification.title}
                        </CardTitle>

                        <Badge variant="outline">
                          {getKindLabel(notification.kind)}
                        </Badge>

                        {!notification.readAt ? <Badge>Unread</Badge> : null}
                      </div>

                      <CardDescription className="mt-1">
                        {notification.outboxEvent.eventType}
                      </CardDescription>
                    </div>

                    {!notification.readAt ? (
                      <form action={markReadAction}>
                        <Button type="submit" variant="ghost" size="sm">
                          <Check className="size-4" />
                          Mark read
                        </Button>
                      </form>
                    ) : null}
                  </div>
                </CardHeader>

                <CardContent>
                  <p className="text-sm">{notification.message}</p>

                  <p className="mt-3 text-xs text-muted-foreground">
                    {new Date(notification.createdAt).toLocaleString()}
                  </p>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </>
  );
}
