services:
  postgres:
    image: postgres:18
    container_name: warehouse-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: warehouse
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_db

    ports:
      - "5432:5432"

    volumes:
      - warehouse_postgres_data:/var/lib/postgresql

volumes:
  warehouse_postgres_data: