FROM node:24.21.0-bookworm-slim AS builder

WORKDIR /workspace

COPY package.json package-lock.json ./

COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY apps/infra/package.json apps/infra/package.json

RUN npm ci \
  --workspace=api \
  --include-workspace-root=false

COPY apps/api apps/api

RUN cd apps/api \
  && npx --no-install prisma generate \
    --config prisma7.config.ts

RUN npm run build --workspace=api


FROM public.ecr.aws/lambda/nodejs:24

WORKDIR ${LAMBDA_TASK_ROOT}

COPY package.json package-lock.json ./

COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY apps/infra/package.json apps/infra/package.json

RUN npm ci \
  --omit=dev \
  --workspace=api \
  --include-workspace-root=false \
  && npm cache clean --force

COPY --from=builder \
  /workspace/apps/api/dist \
  apps/api/dist

CMD ["apps/api/dist/lambda.handler"]